version: '3.8'

services:
  tls-grade-exporter:
    image: ghcr.io/ping7io/tls-grade-exporter:latest
    ports:
      - "9218:9218"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  prometheus_data: