global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tls-grade-exporter'
    metrics_path: /probe
    scrape_interval: 1h
    scrape_timeout: 3m
    static_configs:
      - targets:
        - https://prometheus.io
        - https://ping7.io
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: tls-grade-exporter:9218

  - job_name: 'tls-grade-exporter-metrics'
    static_configs:
      - targets:
        - tls-grade-exporter:9218